# Generated by Django 3.2.9 on 2021-12-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20211209_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
